PORT=8083
server.port=${PORT:8083}

spring.application.name=foodiesapi

# MySQL configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/foodies?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

DB_USERNAME=root
DB_PASSWORD=Bhavik
DB_URL=jdbc:mysql://localhost:3306/foodies?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.username=root
# spring.datasource.password=Bhavik
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#aws s3 configuration
# aws.access.key=dummy_access_key
# aws.secret.key=dummy_secret_key
# aws.region=us-east-1
# aws.s3.bucketname=dummy_bucket

# JWT configuration
jwt.secret.key=secret_key_for_development_must_be_very_long_to_satisfy_hs256_algorithm
jwt.token.expiry=86400000

# razorpay configuration
razorpay_key=rzp_test_S6qsnsT0B6haYc
razorpay_secret=v5xtA0oW2C72DYSClwmzRCOY

#cloudinary configuration
cloud_name= dhhz3ruyc
cloudinary_api_key= 163235312448624
cloudinary_api_secret=ddrAiLaDNUC4qToXKtvFlB-5ptw
